stages:
  prepare:
    cmd: python ml_pipeline/prepare.py
    deps:
      - ml_pipeline/prepare.py
      - uploads
    outs:
      - data/retraining/images
      - data/retraining/dataset_info.json
  
  train:
    cmd: python ml_pipeline/train.py
    deps:
      - ml_pipeline/train.py
      - data/retraining/dataset_info.json
      - data/retraining/images
      - hyperparameters.yaml
    params:
      - hyperparameters.yaml:
          - model_version
          - learning_rate
          - batch_size
          - epochs
          - model_architecture
    outs:
      - models/model_v1.pth:
          persist: true
          cache: false
    metrics:
      - metrics.json:
          cache: false

  evaluate:
    cmd: python ml_pipeline/evaluate.py
    deps:
      - ml_pipeline/evaluate.py
      - models/model_v1.pth
      - hyperparameters.yaml
    metrics:
      - evaluation.json:
          cache: false