# Combined Configuration for Drifted Data Simulation

dataset:
  root_path: './data' # Path where CIFAR-10 is stored/downloaded

output:
  base_image_dir: 'simulated_drift_images' # Base directory to save generated images

# --- Concept Drift Scenarios ---
concept_drift_scenarios:
  concept_airplane_bias: # Name used for sub-directory
    total_samples: 100
    target_distribution:
      0: 0.50  # Airplane 50%
      1: 0.05  # Automobile 5%
      # Proportions for classes 2-9 will be calculated automatically to sum to 1
  concept_dog_bias:
    total_samples: 200 # Generate more samples for this scenario
    target_distribution:
      5: 0.70 # Dog 70%
      3: 0.10 # Cat 10%
      # Proportions for classes 0,1,2,4,6,7,8,9 calculated automatically

# --- Data Drift (Covariate Shift) Scenarios ---
data_drift_scenarios:
  data_brightness_darker: # Name used for sub-directory
    type: 'brightness'
    factor': 0.5 # 0.0 gives black image, 1.0 original
    num_samples: 100
    base_dataset: 'train' # Use 'train' or 'test' set
  data_rotation_moderate:
    type: 'rotation'
    degrees: 30 # Max rotation angle (+/-)
    num_samples: 100
    base_dataset: 'train'
  data_gaussian_noise_low:
     type: 'gaussian_noise'
     mean: 0.0
     std: 0.1 # Adjust standard deviation of noise
     num_samples: 100
     base_dataset: 'train'

# Add more scenarios under the appropriate keys as needed